dataset: 'azure'
map_length: 800
overlap_threshold: 10
mapping:
  vis_freq: 20000
  mesh_freq: 5000
  ckpt_freq: 100
  keyframe_num: 8
  ray_sample: 5000
  iters: 3
  init_iters: 500
  bound: [[-5.8,11.3],[-4.0,4.5],[-7.9,4.9]]
  marching_cubes_bound: [[-5.8,11.3],[-4.0,4.5],[-7.9,4.9]]
cam:
  H: 720 
  W: 1280
  fx: 607.4694213867188
  fy: 607.4534912109375
  cx: 636.9967041015625
  cy: 369.2689514160156
  png_depth_scale: 1000.0 #for depth image in png format
  crop_edge: 0
data:
  input_folder: Datasets/Apartment
  output: output/Apartment
keyframes:
  option: 'filter_depth'
  num_rays_to_save: 10000
  depth_trunc: 4

meshing:
  reso: 512
  clean: False
  